import { Box, Spinner } from '@chakra-ui/react'
import { NextPageContext } from 'next'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Auth from '../components/auth/Auth'
import Chat from '../components/chat/Chat'
import { Session } from 'next-auth'

export default function Home() {
  const { data: session } = useSession()

  console.log(session)

  const reloadSession = () => {}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box color='white'>
        {session?.user?.username ? <Chat /> : <Auth session={session} reloadSession={reloadSession}/>}
      </Box>
    </>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)

  return {
    props: {
      session,
    }
  }
}
